### ISSUE TITLE
JsonOps.convertTo explodes on JsonNulls

### ISSUE THREAD

**Issue by quat1024** [Mojang/DataFixerUpper#62]
```java
public static void main(String[] args) {
	JsonObject j = new JsonObject();
	j.add("test", JsonNull.INSTANCE);
	
	System.out.println(JsonOps.INSTANCE.convertTo(JsonOps.INSTANCE, j)); //should return a copy of `j`
}
```
fails with
```console
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonElement.getAsJsonPrimitive()" because "input" is null
	at com.mojang.serialization.JsonOps.convertTo(JsonOps.java:50)
	at com.mojang.serialization.JsonOps.convertTo(JsonOps.java:24)
	at com.mojang.serialization.DynamicOps.lambda$convertMap$27(DynamicOps.java:255)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at com.mojang.serialization.JsonOps.createMap(JsonOps.java:275)
	at com.mojang.serialization.JsonOps.createMap(JsonOps.java:24)
	at com.mojang.serialization.DynamicOps.convertMap(DynamicOps.java:254)
	at com.mojang.serialization.JsonOps.convertTo(JsonOps.java:42)
	at agency.highlysuspect.apathy.rule.CodecUtil.main(CodecUtil.java:145)
```

It appears there is a check for `instanceof JsonNull`s:
https://github.com/Mojang/DataFixerUpper/blob/c100ef03c2ab321e5de4f25ffbe277e924aa7ca5/src/main/java/com/mojang/serialization/JsonOps.java#L47-L50

but it doesn't work, because `DynamicOps#getJsonValues` filters `JsonNull`s to actual `null`s.
https://github.com/Mojang/DataFixerUpper/blob/c100ef03c2ab321e5de4f25ffbe277e924aa7ca5/src/main/java/com/mojang/serialization/JsonOps.java#L218

**Comment by quat1024** [comment]
The workaround i'm using in my current project (making a `Codec` out of something that has `toJson` and `fromJson` methods, where `toJson` sometimes returns `JsonObject`s containing `JsonNull`s) is just [preprocessing the entire JsonObject and filtering out nulls in objects/arrays](https://github.com/quat1024/apathy/blob/e97a57a326be2e3b31205e9aae20109a80a9fb33/common/src/main/java/agency/highlysuspect/apathy/rule/CodecUtil.java#L98-L122).
